# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

surrosurvoCpp <- function(df, n) {
    .Call(`_surrosurvo_surrosurvoCpp`, df, n)
}

confintCpp <- function(df, n, nthread) {
    .Call(`_surrosurvo_confintCpp`, df, n, nthread)
}

